language : c
compiler : gcc
os : linux

before_install:
    - pip install --user cpp-coveralls

script :
    - make -C src/core -j8
    - ./src/core/build/test
    - make -C src/client -j8
    - ./src/client/build/test -h
    - ./src/client/build/test pub -t 'test/topic' -m 'QoS0' -q 0
    - ./src/client/build/test pub -t 'test/topic' -m 'QoS1' -q 1
    - ./src/client/build/test pub -t 'test/topic' -m 'QoS2' -q 2
    - ./src/client/build/test sub -t 'test/topic' -n 1

after_success:
    - coveralls --exclude=src/core/test.c --gcov-options '\-lp'

