language : c
compiler : gcc
os : linux
# Handle git submodules yourself
git:
    submodules: false
before_install:
    - pip install --user cpp-coveralls
    - sudo apt-get install mosquitto
    - git config --file=.gitmodules submodule.AT-interpreter.url https://github.com/Shylock-Hg/AT-interpreter.git
    - git submodule update --init --recursive

before_script:
    - mosquitto -d

script :
    - ps -aux | grep mosquitto
    - make -C src/core -j8
    - ./src/core/build/test
    - make -C src/client -j8
    - ./src/client/build/test -h
    - ./src/client/build/test pub -t 'test/topic' -m 'QoS0' -q 0
    - ./src/client/build/test pub -t 'test/topic' -m 'QoS1' -q 1
    - ./src/client/build/test pub -t 'test/topic' -m 'QoS2' -q 2
    - ./src/client/build/test sub -t 'test/topic' -n 1
      #    - cd src/at
      #    - make && ./build/test

after_success:
    - coveralls --gcov-options '\-lp'

