language : c
compiler : gcc
os : linux
# Handle git submodules yourself
git:
    submodules: false
before_install:
    - sudo apt-get install xsltproc docbook-xsl
    - git clone --depth=1 https://github.com/eclipse/mosquitto.git && cd mosquitto && make -j8 && sudo make install && cd ..
    - sudo pip install cpp-coveralls
    - git config --file=.gitmodules submodule.AT-interpreter.url https://github.com/Shylock-Hg/AT-interpreter.git
    - git submodule update --init --recursive

before_script:
    - mosquitto -d

script :
    - sudo make install -j8
    - export LD_LIBRARY_PATH=/usr/local
    - mqttor_client -h
    - mqttor_client pub -t 'test/topic' -m 'QoS0' -q 0
    - mqttor_client pub -t 'test/topic' -m 'QoS1' -q 1
    - mqttor_client pub -t 'test/topic' -m 'QoS2' -q 2
    - mqttor_client sub -t 'test/topic' -n 1

after_success:
    - coveralls --gcov-options '\-lp'

